# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/id_grupo_07',
                'doc_host': 'https://dci-courses.github.io',
                'git_url': 'https://github.com/dci-courses/id_grupo_07',
                'lib_path': 'id_grupo_07'},
  'syms': {'id_grupo_07.core': {'id_grupo_07.core.foo': ('core.html#foo', 'id_grupo_07/core.py')}}}
