name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies including Jupyter
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbdev jupyter

      # Deploy with Quarto and GitHub Pages
      - name: Deploy to GitHub Pages
        uses: fastai/workflows/quarto-ghp@master
